### ISSUE TITLE
Configure xvfb for travis, so we can do automatic testing.

### ISSUE THREAD

**Issue by joshimoo** [joshimoo/gdi1-project#80]
Thanks for getting in touch. A common solution to this problem is to use xvfb, as described here: http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser). I hope this helps!

**Comment by tuCharly** [comment]
:+1:

**Comment by joshimoo** [comment]
cannot run, lwjgl2 inside of travis
would require an upgrade to lwjgl3 which is not compatible with the abandoned slick2d
so for now I am disabling travis, see 2d9c7bf91ae0886facdbbf345cc470cb52e20680
